apiKey: "c4"
currentWeatherByZipUrl: "https://api.openweathermap.org/data/2.5/weather?zip=%s&appid=%s"

# imperial, metric
unit: "imperial"

# EN FR RU
lang: "EN"

# Accepted log levels are: info, debug, error, warning
loglevel: "DEBUG"

# time in sec
pollInterval: 10

locations:
  - "95134"

redis:
  addr: "localhost:6379"
  password: ""
  db: ""